### ISSUE TITLE
train has high ```top1.avg```  but predict has bad result, same data to predict,why?

### ISSUE THREAD

**Issue by jaffe-fly** [Alibaba-MIIL/ImageNet21K#10]
i use ```vit_base_patch16_224_in21k``` model, when i train with pretrained model,it has high ```top1.avg``` .about 99 %.
but when i use same data(train data) to predict ,the resutl very bad!!,i dont know why,can you give me some idea?

**Comment by mrT23** [comment]
not really, seems like a bug in your scripts.

try a different model (renset50) to verify. 
make sure you are properly loading the model from memory for predictions.

**Comment by jaffe-fly** [comment]
I use latest timm, it will error 

```
  File "/home/wangzf/wzf/lib/python3.6/site-packages/timm/models/vision_transformer.py", line 416, in _create_vision_transformer
    **kwargs)
  File "/home/wangzf/wzf/lib/python3.6/site-packages/timm/models/helpers.py", line 455, in build_model_with_cfg
    strict=pretrained_strict)
  File "/home/wangzf/wzf/lib/python3.6/site-packages/timm/models/helpers.py", line 209, in load_pretrained
    del state_dict[classifier_name + '.weight']
KeyError: 'head.weight
```

**Comment by mrT23** [comment]
- this error relates to timm package, not to 21K pretraining.
- see an example for transfer learning code in: https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/Transfer_learning.md
- try maybe adding: --nonstrict_checkpoint flag.
