### ISSUE TITLE
Some confuse on processing to link wikidata

### ISSUE THREAD

**Issue by wtt0213** [Alibaba-MIIL/ImageNet21K#11]
Dear author ：
Thank you for your awesome idea ！
I have two questions :
1、If the label of the parent node does not appear in origin label set, how do you deal with it ?
2、When I use WordNet.hypernyms(), sometimes it will return multi parents for one synsetid, how do you deal with it?
3、How do you set the 0~11 level, if you just use the number of its parents, when a node have two parents, obviously it will get the wrong level, besides that, the labels may have some overlaps cross different levels, how do you get over it?

Looking for you apply

**Comment by mrT23** [comment]
- i used https://github.com/niharikajainn/imagenet-ancestors-descendants/blob/master/is_a.txt to create the semantic tree
- all imagenet21K labels are there
- a node can only have one direct parent. this is how WordNet was constructed
