### ISSUE TITLE
ImageNet 21K-P Class ID:Name mapping

### ISSUE THREAD

**Issue by ArikVoronovRazor** [Alibaba-MIIL/ImageNet21K#12]
Hi!

Thanks for the great repo!

I'm using timm to load your pretrained models.
The "_in21k" variants (e.g tresnet_m_miil_in21k) output 11221 classes in the final layer, 
which seems to be the amount of classes in the [Fall 11 Version](https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/dataset_preprocessing/processing_instructions.md).

Where can I find the mapping from the model output to the class names/wordnet IDs?

**Comment by mrT23** [comment]
see an example in
https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/visualize_detector.py
(line 64)
