### ISSUE TITLE
How did everyone get their ImageNet-21K?

### ISSUE THREAD

**Issue by kaizhaol** [Alibaba-MIIL/ImageNet21K#14]
"ImageNet-21K-P processed dataset, based on ImageNet-21K winter release, is now available for easy downloading via the offical ImageNet site."

No responses or permission granted since last year. Need help

**Comment by mrT23** [comment]
make sure you provide them an academic email address. permission is usually given in a couple of minutes

**Comment by kaizhaol** [comment]
Got it, thanks
