### ISSUE TITLE
processing for winter21-whole

### ISSUE THREAD

**Issue by cissoidx** [Alibaba-MIIL/ImageNet21K#16]
Hello, thanks for your great work.
I am confused about different versions of the dataset. As far as I understand, we here have the following version:

- fall11_whole.tar, size 1.3T, 21841 classes
- ImageNet-21K-P  based on fall1 release could be obtained using the `processing_script.sh`, 11221 classes

- winter21_whole.tar.gz, size 1.1T, 19167 classes
- ImageNet-21K-P based on winter21 release could be (or not) using the `processing_script.sh`, 10450 classes

My question is: can I use the `processing_script.sh` to process winter21_whole.tar.gz to get the so-called variant that has 10450 classes?

**Comment by mrT23** [comment]
yes

**Comment by lianzheng-research** [comment]
Thanks for your excellent work! I need some help.
I find winter21_whole.tar.gz on "https://image-net.org/download-images.php".
But I don't find fall11_whole.tar. How can I access to this dataset?
Thank you very much!
