### ISSUE TITLE
Where can I download winter21_imagenet21k_miil_tree.pth

### ISSUE THREAD

**Issue by Yuzz1020** [Alibaba-MIIL/ImageNet21K#18]
Hi, 

Thank you for sharing your great work! I am currently running with the Winter 21 Version of the ImageNet-21k-P dataset. But I cannot find the link to the semantic tree file winter21_imagenet21k_miil_tree.pth you mentioned in this [page](https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/dataset_preprocessing/processing_instructions.md). Do you know where can I get this file? 

Thank you for your time!

**Comment by mrT23** [comment]
https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/resources/winter21_imagenet21k_miil_tree.pth

**Comment by Yuzz1020** [comment]
Thank you for sharing!
