### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by KleinXin** [Alibaba-MIIL/ImageNet21K#20]
HotelID is a dataset that has similar hierarchical architecture as Imagenet21k. 
https://arxiv.org/abs/2106.05746
So I want to try to use this project to train on that dataset.

The question is in that case, each chain_id has many sub-hotels, this means the parent of the chain_id class is itself when genrating the 'semantic tree'.  

Do you think it can give reasonable results?

**Comment by mrT23** [comment]
your tree doesn't have lots of depth (only 2 possible hierarchies if i understand correctly).
so  a simple 2 softmax solution seems reasonable.
