### ISSUE TITLE
For a customized dataset, how to build a semantic tree and how to match them with the label defined by pytorch ImageFolder?

### ISSUE THREAD

**Issue by aiot-tech** [Alibaba-MIIL/ImageNet21K#23]
after reading all the issues, I still don’t understand how to build the tree...

**Comment by mrT23** [comment]
the semantic tree is only relevant for datasets derived from wordnet hierarchies (a.ka ImageNet)

**Comment by aiot-tech** [comment]
thanks! But for a customize dataset, how to generate the tree?

**Comment by mrT23** [comment]
the tree is not relevant for a customize dataset

**Comment by aiot-tech** [comment]
aha，thank you very much!
