### ISSUE TITLE
About Multi-label Training Scheme

### ISSUE THREAD

**Issue by SJLeo** [Alibaba-MIIL/ImageNet21K#24]
I want to know how to get multi-label information of each image. It doesn't contain these information in winter21_whole.tar.gz.

**Comment by mrT23** [comment]
review thoroughly https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/train_semantic_softmax.py file.

specifically the conversion is done in
https://github.com/Alibaba-MIIL/ImageNet21K/blob/00ef9989825bbcb8dedc91eac18638c129eb5ad8/src_files/semantic/semantic_loss.py#L5
line 20

**Comment by aiot-tech** [comment]
Does the multi-label here refer to the multi-label of the same kind of the sematic tree, such as animal-dog-border_collie? But if a picture contains multiple different types of labels, such as animal-dog-border_collie, human-woman-young_woman, how to solve this problem?

**Comment by SJLeo** [comment]
So you extract the meaning of each category in imagenet22k, and then use wordnet to construct a semantic tree. Finally, the semantic tree is used to generate multi-label information for each category, that is, the multi-label information of all images in each directory of imagenet22k is the same.

**Comment by mrT23** [comment]
> So you extract the meaning of each category in imagenet22k, and then use wordnet to construct a semantic tree. Finally, the semantic tree is used to generate multi-label information for each category, that is, the multi-label information of all images in each directory of imagenet22k is the same.

i did not understand if there is a question or not. your description seems correct

**Comment by mrT23** [comment]
> Does the multi-label here refer to the multi-label of the same kind of the sematic tree, such as animal-dog-border_collie? But if a picture contains multiple different types of labels, such as animal-dog-border_collie, human-woman-young_woman, how to solve this problem?

it won't. the base tagging of original imagenet21K is single label.

**Comment by SJLeo** [comment]
Where can I find the mapping between class ids and class names?

**Comment by mrT23** [comment]
https://raw.githubusercontent.com/niharikajainn/imagenet-ancestors-descendants/master/words.txt

**Comment by SJLeo** [comment]
Thank you very much

**Comment by SJLeo** [comment]
Could you provide the code of how to get the multi-label of each image according to words.txt file

**Comment by cissoidx** [comment]
> Could you provide the code of how to get the multi-label of each image according to words.txt file

same question here

**Comment by cissoidx** [comment]
> Could you provide the code of how to get the multi-label of each image according to words.txt file

https://github.com/niharikajainn/imagenet-ancestors-descendants

**Comment by mrT23** [comment]
> Could you provide the code of how to get the multi-label of each image according to words.txt file

all the transformation and semantic data can be found in the resource file. make sure you review it thoroughly
https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/resources/winter21/imagenet21k_miil_tree.pth

you are also welcome to validate them via the link @cissoidx  sent (that was my source for generating the tree)

**Comment by SJLeo** [comment]
Could you provide the code of how to generating the tree

**Comment by mrT23** [comment]
No at the moment. you are welcome to write a code of your own and validate my results.

**Comment by SJLeo** [comment]
Thank you very much
