### ISSUE TITLE
General fail in preprocessing

### ISSUE THREAD

**Issue by cissoidx** [Alibaba-MIIL/ImageNet21K#25]
I did a full preprocessing using your script on the winter21_whole.tar.gz dataset. Is it normal to have tons of general fail messages? Will these fails of images impact final training results?
![截屏2021-07-05 下午6 35 15](https://user-images.githubusercontent.com/17111388/124458599-c34c9480-ddbf-11eb-9180-d92d26c09790.png)

**Comment by mrT23** [comment]
no

**Comment by cissoidx** [comment]
@mrT23 thanks for reply.
Have you tried this script on the recently released winter21_whole.tar.gz dataset on you own? It seems the resizing process is running normally, but the there are bad images in it. what is the md5sum of the winter21_whole.tar.gz file?
![截屏2021-07-06 下午12 09 16](https://user-images.githubusercontent.com/17111388/124540943-fe4bd800-de52-11eb-9ec0-c95cafd81da7.png)

**Comment by mrT23** [comment]
no. i processed fall11 variant.
winter21 variant was processed by image-net.org. notice that they offer the processed version for direct download, so 
maybe you dont need to process it by yourself.
you can also contact them regarding the errors.

**Comment by cissoidx** [comment]
cannot find the download link. I only have the winter21_whole.tar.gz for the moment.

**Comment by mrT23** [comment]
![image](https://user-images.githubusercontent.com/21198860/124606133-41b73e00-de75-11eb-9281-a34099beb2d3.png)

**Comment by cissoidx** [comment]
thanks for info

**Comment by cissoidx** [comment]
FYI, the md5 of my copy of the dataset  matches the one shown above. So I guess there are indeet corrupted images in this tar file.

ab313ce03179fd803a401b02c651c0a2  winter21_whole.tar.gz

**Comment by mrT23** [comment]
@cissoidx 
so contact image-net.org and let them know. i did not create this file.

**Comment by cissoidx** [comment]
<img width="421" alt="截屏2021-07-10 下午5 49 29" src="https://user-images.githubusercontent.com/17111388/125159014-519d8d80-e1a7-11eb-9e82-8f64ecb388b1.png">

It seems I have one more image in training set than what you stated in the `processing_instructions.md` file although I had several tens of general failures. Imagenet.org does not validate my email, cannot contact them.

**Comment by cissoidx** [comment]
where do you get the following files:
```python
files_train_set = './resources/datasets_imagenet21K_P_train_folder_index.pkl'
files_val_set = './resources/datasets_imagenet21K_P_val_folder_index.pkl'
```
Could you please provide download links?

**Comment by cissoidx** [comment]
@mrT23 can you please provide these pkl files?

**Comment by mrT23** [comment]
they are for fall11. you are processing winter21, so they won't help you

**Comment by cissoidx** [comment]
ok. thanks for reply
