### ISSUE TITLE
如何用resnet50加载21k pertained

### ISSUE THREAD

**Issue by daixiangzi** [Alibaba-MIIL/ImageNet21K#27]

**Comment by daixiangzi** [comment]
model = timm.create_model('resnet50_mill_in21k', pretrained=True)这么做好像无效

**Comment by daixiangzi** [comment]
另外我把你们的权重下下来了,用标准的pytorch方式加载也会出现错误

**Comment by mrT23** [comment]
```
    import timm
    from src_files.models.utils.factory import load_model_weights
    model = timm.create_model('resnet50', pretrained=False)
    model =load_model_weights(model, './resnet50_miil_21k.pth')
```

**Comment by daixiangzi** [comment]
谢谢



我没有什么天赋，我只是生而由来的执着。


------------------ 原始邮件 ------------------
发件人: mrT23 ***@***.***&gt;
发送时间: 2021年7月7日 00:19
收件人: Alibaba-MIIL/ImageNet21K ***@***.***&gt;
抄送: daixiangzi ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Alibaba-MIIL/ImageNet21K] 如何用resnet50加载21k pertained (#27)





     import timm     from src_files.models.utils.factory import load_model_weights     model = timm.create_model('resnet50', pretrained=False)     model =load_model_weights(model, './resnet50_miil_21k.pth')

**Comment by daixiangzi** [comment]
> ```
>     import timm
>     from src_files.models.utils.factory import load_model_weights
>     model = timm.create_model('resnet50', pretrained=False)
>     model =load_model_weights(model, './resnet50_miil_21k.pth')
> ```

model = timm.create_model('resnet50', pretrained=False,num_classes=11221) is right
