### ISSUE TITLE
Model weights trained on Stanford cars

### ISSUE THREAD

**Issue by ma-siddiqui** [Alibaba-MIIL/ImageNet21K#28]
Hi,

Can you please share the link to the weights file of model trained on Stanford cars data set. I am unable to get the expected results  using https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/models/tresnet_l_v2_miil_21k.pth

Please guide.

Thanks,

**Comment by ma-siddiqui** [comment]
fortunately found here. Please correct me if this is not a correct link

https://github.com/Alibaba-MIIL/TResNet

**Comment by mrT23** [comment]
yep
https://github.com/Alibaba-MIIL/TResNet/blob/master/MODEL_ZOO.md

**Comment by ma-siddiqui** [comment]
Thank you. What is the correct model architecture for these weights? Should I use imageNet21K or original TresNet repo. Actually I faced some errors using the code TresNet repo.

**Comment by mrT23** [comment]
if you faced errors, give full reproduction code. use the model LTResNet-V2 form tresnet repo

**Comment by ma-siddiqui** [comment]
Hi,

I am facing below errors

File "TResNet/infer.py", line 44, in <module>
    main()
  File "TResNet/infer.py", line 26, in main
    model = create_model(args).cuda()
  File "TResNet/src/models/utils/factory.py", line 23, in create_model
    model = TResnetL_V2(model_params)
  File "TResNet/src/models/tresnet_v2/tresnet_v2.py", line 239, in TResnetL_V2
    model = TResNetV2(layers=layers_list, num_classes=num_classes, in_chans=in_chans,
  File "TResNet/src/models/tresnet_v2/tresnet_v2.py", line 160, in __init__
    layer2 = self._make_layer(Bottleneck, self.planes * 2, layers[1], stride=2, use_se=True,
  File "TResNet/src/models/tresnet_v2/tresnet_v2.py", line 215, in _make_layer
    layers.append(block(self.inplanes, planes, stride, downsample, use_se=use_se,
  File "TResNet/src/models/tresnet_v2/tresnet_v2.py", line 117, in __init__
    anti_alias_layer(channels=planes, filt_size=3, stride=2))
TypeError: __init__() got an unexpected keyword argument 'remove_model_jit'


Thanks,
