### ISSUE TITLE
Normalize

### ISSUE THREAD

**Issue by akuxcw** [Alibaba-MIIL/ImageNet21K#29]
Thank you for this awesome work! I want to make sure that you only rescale the input image to 0-1 instead of normalizing them by (img-mean)/std like we usually do in ImageNet training. Is that right?

**Comment by mrT23** [comment]
correct.
the mean,std normalization doesn't contribute anything in practice

**Comment by akuxcw** [comment]
Thanks! Just a piece of advice, you may declare this normalization strategy somewhere. Because it's important to align the input scales for the downstream tasks.
