### ISSUE TITLE
how to use DPP to start ```train_single_label.py```

### ISSUE THREAD

**Issue by jaffe-fly** [Alibaba-MIIL/ImageNet21K#3]
1  machine 2 GPUs
I cant use command line to start 
how to start in the wInternal code  to use DDP

i cant find where to save mode, how to save in the DDP

**Comment by mrT23** [comment]
give more details when you open an issue. what have you tried ?

Anyway, for DDP use stanard PyTorch multi-GPU command:
`python -u -m torch.distributed.launch --nproc_per_node=2 train_single_label.py`

currently, the script does not save the model. there is no special saving of DDP model, just torch.save(...) (on rank==0 only of course).
you are welcome to open a merge request for adding the saving feature.

**Comment by jaffe-fly** [comment]
when i use the above command 
`
root@1ebda974bc7a:/home/ImageNet21K# python -u -m torch.distributed.launch --nproc_per_node=2 train_single_label.py --batch_size=4 --data_path=/mnt/dataset --model_name=mobilenetv3_large_100 --model_path=/home/ImageNet21K/mobilenetv3_large_100_miil_21k.pth --epochs=10
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
creating model mobilenetv3_large_100...
creating model mobilenetv3_large_100...
done

done


`

the progarm seems block   stop and not  continue

**Comment by Stephen-Hao** [comment]
By using "python -u -m torch.distributed.launch --nproc_per_node=2 train_single_label.py",I encounter the same problem

**Comment by mrT23** [comment]
@jaffe-fly thanks for the feedback
i changed the order,  'torch.distributed.init_process_group' should be before model initialization.
please update and let me know if it was fixed.

**Comment by Stephen-Hao** [comment]
![image](https://user-images.githubusercontent.com/35420905/118345709-ef3e5d00-b568-11eb-9021-819846010d5e.png)


@mrT23 Now it works well,Thanks alot!

**Comment by jaffe-fly** [comment]
@mrT23  its ok   thank you

but one warining
```
UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
```

**Comment by mrT23** [comment]
thanks @jaffe-fly and @Stephen-Hao 

the warning on lr_scheduler does not hurt the training results.
