### ISSUE TITLE
How to download semantic tree: winter21_imagenet21k_tree.pth?

### ISSUE THREAD

**Issue by zlenyk** [Alibaba-MIIL/ImageNet21K#32]
I can't find anywhere semantic tree for the winter_21 version with 10450 classes.
I don't think there's any working link provided in this repo or in image-net.org
Could you point me to the file?

Thank you

**Comment by mrT23** [comment]
i updated the readme file with the link

https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/resources/winter21/imagenet21k_miil_tree.pth

**Comment by zlenyk** [comment]
It looks good, thank you very much!
