### ISSUE TITLE
Which version is imagenet21k_resized.tar.gz ?

### ISSUE THREAD

**Issue by Felix-Petersen** [Alibaba-MIIL/ImageNet21K#37]

**Comment by Felix-Petersen** [comment]
Which version lies behind:
https://image-net.org/data/imagenet21k_resized.tar.gz

I mean, is it based on the 2011 or the 2021 release of full ImageNet?
The paper states that both versions would be available preprocessed.

**Comment by mrT23** [comment]
thoroughly review the readme file before opening an issue like that
