### ISSUE TITLE
I want to speed up the tresnet_m go a step further by modifying the structure

### ISSUE THREAD

**Issue by Stephen-Hao** [Alibaba-MIIL/ImageNet21K#4]
I want to speed up the tresnet_m go a step further, if I modify the bottlebneck strcture"[3,4,11,3]" to "[3,4,8,3]"，the network can work  too. Do you compare the modified "[3,4,8,3]" or "[3,4,6,3]" to standard resnet50"[3,4,6,3]" about accurancy and speed? Thank you a lot

**Comment by mrT23** [comment]
i tried a model called TResNet-S (S for small) with [3,4,7,3].  didn't put it in the paper

i don't fully remember what's its accuracy was, but it was both faster and more accurate than resnet50.
In the end, just changing the number of blocks in the 3rd stage will move you on the Pareto curve - a faster model, with lower accuracy. it won't bring significant improvement to the speed-accuracy tradeoff.

**Comment by Stephen-Hao** [comment]
Thank you very much!
