### ISSUE TITLE
The strategy of transferring ImageNet-21k ViT model to cifar100

### ISSUE THREAD

**Issue by Dyfine** [Alibaba-MIIL/ImageNet21K#40]
Hi @mrT23, thanks for your great work! Currently I use timm train.py to finetune the 'vit_base_patch16_224_miil_in21k' model on cifar100, however I can't get the reported result 94.2%. 
Here is my running script.
```
python -m torch.distributed.launch --nproc_per_node=8 --master_port 6016 train.py \
/data/cifar-100-images/ \
-b=64 \
--img-size=224 \
--epochs=50 \
--color-jitter=0 \
--amp \
--lr=2e-4 \
--sched='cosine' \
--model-ema --model-ema-decay=0.995 --reprob=0.5 --smoothing=0.1 \
--min-lr=1e-8 --warmup-epochs=3 --train-interpolation=bilinear --aa=v0 \
--model=vit_base_patch16_224_miil_in21k \
--pretrained \
--num-classes=100 \
--opt=adamw --weight-decay=1e-4 \
--checkpoint-hist=1
```
I try several settings:
adam, lr=2e-4, wd=1e-4  92.44%
adamw, lr=2e-4, wd=1e-4  92.90%
sgd, lr=2e-4, wd=1e-4  87.49%
adamw, lr=4e-4, wd=1e-4  92.24%
adamw, lr=2e-4, wd=1e-2  93.08%
Could you give me some suggestions?

**Comment by mrT23** [comment]
93.1% is an extremely high score. be happy.
it is higher than what google reported in their paper, and until 1-2 years ago it would have been SOTA on cifar-100.

i didn't use timm for training, so i don't have an exact recipie for timm. anyway, i used
 --batch_size=128 --optimizer=sgd --learning_rate=1e-2 --wd=1e-4
 it should bring you close 94% (hopefully)

**Comment by Dyfine** [comment]
Thank you very much! Sorry for the late reply, I have followed your training setting above, i.e., bs=128, sgd, lr=1e-2, wd=1e-4, with some other settings: the same data augmentation as semantic_softmax pretrain, one-cycle policy, label_smooth=0.1, epochs=40, and I finally get 93.76% top-1 acc.

**Comment by yhydhx** [comment]
> 

Hi Dyfine:

Could you tell me the format of cifar-100 folder? Appreciate so much!

Best,
Harold.

**Comment by Dyfine** [comment]
Hi~ @yhydhx, below is the detailed format
```
└───cifar-100-images
    └───train
    |   └───apple
    |       └───apple_s_000027.png
    |       └───...
    |   └───aquarium_fish
    |       └───...
    |   └───...
    └───test
    |   └───apple
    |       └───apple_s_000022.png
    |       └───...
    |   └───aquarium_fish
    |       └───...
    |   └───...

```

**Comment by yhydhx** [comment]
Hi @Dyfine , sorry for the late response. It works!
Thank you very much!
