### ISSUE TITLE
About downstream tasks

### ISSUE THREAD

**Issue by SJLeo** [Alibaba-MIIL/ImageNet21K#41]
In order to verify the effectiveness of ImageNet-21k dataset pretraining. I modified the Faster RCNN configuration file in mmdetection, only point the path of the backbone resnet50 pretraining weights to the 21k trained model but achieved worse results than the torchvision pretraining weights

**Comment by mrT23** [comment]
this issue is not written in a polite manner, hence will be closed.
if you want to engage in a proper discussion, open a new issue, in a much more polite and informative manner
