### ISSUE TITLE
ImageNet-1K Metadata 

### ISSUE THREAD

**Issue by Auth0rM0rgan** [Alibaba-MIIL/ImageNet21K#49]
Hi @mrT23, I want to do the inference on ImageNet 1K but do know where can i download the metadatas. would you please tell me where can i find the metadata for ImageNet1K?

Thanks!

**Comment by mrT23** [comment]
what is "metadatas"  if imagenet1K ?

class number to names can be found easily via google search

**Comment by Auth0rM0rgan** [comment]
In the `visualize_detector.py`, you are loading the metadata for ImageNet21K as follow

```
############### Downloading metadata ##############
print("downloading metadata...")
url, filename = (
    "https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/resources/fall11/imagenet21k_miil_tree.pth",
    "imagenet21k_miil_tree.pth")
if not os.path.isfile(filename):
    urllib.request.urlretrieve(url, filename)
args = Namespace()
args.tree_path = filename
semantic_softmax_processor = ImageNet21kSemanticSoftmax(args)
print("done")

```

I want to do inference for ImageNet1K but I dont where to find the `???.pth` file for ImageNet1K

**Comment by mrT23** [comment]
the script is intended only for ImageNet21K models
