### ISSUE TITLE
Can you share mean, std of imagenet21k?

### ISSUE THREAD

**Issue by ooodragon94** [Alibaba-MIIL/ImageNet21K#51]
thanks for your code share

If possible, can you share me the mean and std of imagenet 21k? thanks!

**Comment by mrT23** [comment]
no.

the usage of "mean" and "std" is highly redundant.

use simple normalization 0-255 -> 0-1, as the code and paper proposes.

**Comment by ooodragon94** [comment]
thank you for your clarification!
