### ISSUE TITLE
Is the 1k validation set included in the 21k data？

### ISSUE THREAD

**Issue by Bo396543018** [Alibaba-MIIL/ImageNet21K#52]
Whether the data in the 1k val set will be included in the 21k, and if so, will it lead to the valset result a little high？

**Comment by mrT23** [comment]
already asked and answered.
no

![image](https://user-images.githubusercontent.com/21198860/147536866-74001d88-2555-4578-abf7-a0e7871b2bf4.png)

**Comment by Bo396543018** [comment]
Sorry for not seeing this, thanks again
