### ISSUE TITLE
About hierarchy balancing

### ISSUE THREAD

**Issue by hankyul2** [Alibaba-MIIL/ImageNet21K#53]
Hello, Thank you for sharing your work!!!! 😀

During reading your paper, I got a question about some equation. (shown below picture)

![image](https://user-images.githubusercontent.com/31476895/147620838-3d374eca-5c3c-4ebc-9574-827b3a920f5b.png)

My questions in equation (2) are follow:
- Does `k` means hierarchical layer number?
- If `k` is large, `O_k` means softmax at low higher hierarchies in ?

![in21k_pretraining_question](https://user-images.githubusercontent.com/31476895/147621419-67b6043b-2911-4553-a2cb-c98d4eaedd05.jpg)

Again, thank you for sharing your great work!!!

**Comment by mrT23** [comment]
Does k means hierarchical layer number - yes

![image](https://user-images.githubusercontent.com/21198860/147633113-1206e2fe-30a7-4644-9de4-c4431d0740f1.png)

The arxiv version of the paper had a mistake. i already corrected it in the NeurIPS version:
https://openreview.net/pdf?id=Zkj_VcZ6ol
![image](https://user-images.githubusercontent.com/21198860/147633502-5cd23246-fc41-46e9-bd3d-ee2be9a1588e.png)
Maybe i should also release a new arxiv version, to prevent further confusion.

kudos for the thorough reading.

**Comment by hankyul2** [comment]
@mrT23 Thank you for your kind reply. I understand formular now.
