### ISSUE TITLE
can't download metadata

### ISSUE THREAD

**Issue by ghkhk** [Alibaba-MIIL/ImageNet21K#8]
i tried to run visualize_detector.py, but there is a httperror 

urllib.request.urlretrieve(url, filename)

Exception has occurred: HTTPError
HTTP Error 403: Forbidden

how can it be solved?

**Comment by mrT23** [comment]
i think its a problem of your environment. can you download anything with urlib ?

anyway, download and input a picture manually if urlib doesnt work

**Comment by ghkhk** [comment]
Yes. I downloaded the dog image, but imagenet21k_tree.pth didn't be downloaded.

**Comment by mrT23** [comment]
ok, i saw the problem. thanks for the feedback.

try now, should work

**Comment by ghkhk** [comment]
Thank you

**Comment by DylanTao** [comment]
@mrT23 I am trying the same thing now and downloading imagenet21k_tree.pth is again giving 403. Could you help with that?

**Comment by mrT23** [comment]
@DylanTao both link work for me. try again, and check for inner network problems

**Comment by DylanTao** [comment]
Hello, @mrT23, I tried using VPN to access from multiple geo-locations, but I am still getting 403. Is it possible there eixst certain credential in your machine that allows access?

**Comment by mrT23** [comment]
@DylanTao found the problem
i updated the links in the readme file, but not in the script.
try again now

**Comment by DylanTao** [comment]
Issue solved, thanks so much.
