### ISSUE TITLE
Request for ImageNet-1k KD results

### ISSUE THREAD

**Issue by RuiFeiHe** [Alibaba-MIIL/ImageNet21K#9]
Hi, I'm impressed by your great work! I'm wondering would it be possible for you to release the model checkpoints after you trained from the pre-trained ImageNet-21k-P weights by your semantic KD on ImageNet-1k, which are the models in your Table6. I believe it would be more convincing if others could directly test your model on ImageNet-1k.

**Comment by mrT23** [comment]
The following 1K (+KD) models are avaialble on the timm package.
model = timm.create_model('mobilenetv3_large_100_1k_miil', pretrained=True)
model = timm.create_model('tresnet_m', pretrained=True)
model = timm.create_model('vit_base_patch16_224_1k_miil', pretrained=True)
model = timm.create_model('mixer_b16_224_miil', pretrained=True)

there are already inference results in:
https://github.com/rwightman/pytorch-image-models/blob/master/results/results-imagenet.csv
